### ISSUE TITLE
I can run the text portion with no problems but then I'm not able to generate the video.Help

### ISSUE THREAD

**Issue by iteachpc** [pythontester192/AI-Video-Generator-Using-OpenAI-Python#3]
C:\ai video generator>python video_generator.py
Generate New AI Image From Paragraph...
The Generated Image Saved in Images Folder!
The Paragraph Converted into VoiceOver & Saved in Audio Folder!
Extract voiceover and get duration...
Extract Image Clip and Set Duration...
Customize The Text Clip...
Traceback (most recent call last):
  File "C:\Users\iteac\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\video\VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "C:\Users\iteac\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\tools.py", line 46, in subprocess_call
    proc = sp.Popen(cmd, **popen_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iteac\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\iteac\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ai video generator\video_generator.py", line 52, in <module>
    text_clip = TextClip(para, fontsize=50, color="white")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iteac\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\video\VideoClip.py", line 1146, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

[WinError 2] The system cannot find the file specified.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

**Comment by tegast** [comment]
You should **install** [ImageMagick](https://imagemagick.org/script/download.php#windows)

**Comment by singhenter21** [comment]
same problem i am also facing
