### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details Issue

### ISSUE THREAD

**Issue by singhjagtar0290** [pythontester192/AI-Video-Generator-Using-OpenAI-Python#7]
When I tried to generate the content,It is always giving the below error

What topic you want to write about: Say this is a test
The AI BOT is trying now to generate a new text for you...
Traceback (most recent call last):
  File "C:\Users\jagtar\Downloads\AI-Video-Generator-Using-OpenAI-Python-main\text_generator.py", line 16, in <module>
    completions = openai.Completion.create(
  File "C:\Users\jagtar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\jagtar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\jagtar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\jagtar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\jagtar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Comment by singhjagtar0290** [comment]
This was fixed but uploading the credit card details in openai account

**Comment by elghaouti** [comment]
https://paste.fo/raw/ba188f25eaf3 
!!!!!
